# coding: utf-8

"""
    Mainnet Cash

    A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0.   # noqa: E501

    The version of the OpenAPI document: 2.3.10
    Contact: hello@mainnet.cash
    Generated by: https://openapi-generator.tech
"""


from __future__ import absolute_import

import unittest
import datetime

import mainnet
from mainnet.models.history_response import HistoryResponse  # noqa: E501
from mainnet.rest import ApiException

class TestHistoryResponse(unittest.TestCase):
    """HistoryResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional):
        """Test HistoryResponse
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # model = mainnet.models.history_response.HistoryResponse()  # noqa: E501
        if include_optional :
            return HistoryResponse(
                transactions = [
                    mainnet.models.transaction_history_item.TransactionHistoryItem(
                        to = '0', 
                        from = '0', 
                        unit = mainnet.models.unit_type.UnitType(), 
                        index = 1.337, 
                        blockheight = 1.337, 
                        txn = '0', 
                        tx_id = '0', 
                        value = 1.337, 
                        fee = 1.337, 
                        balance = 1.337, )
                    ]
            )
        else :
            return HistoryResponse(
        )

    def testHistoryResponse(self):
        """Test HistoryResponse"""
        inst_req_only = self.make_instance(include_optional=False)
        inst_req_and_optional = self.make_instance(include_optional=True)


if __name__ == '__main__':
    unittest.main()
