# coding: utf-8

"""
    Mainnet Cash

    A developer friendly bitcoin cash wallet api  This API is currently in *active* development, breaking changes may be made prior to official release of version 1.0.0.   # noqa: E501

    The version of the OpenAPI document: 4.0.0-next.13
    Contact: hello@mainnet.cash
    Generated by: https://openapi-generator.tech
"""


import pprint
import re  # noqa: F401

import six

from mainnet.configuration import Configuration


class TokenBurnItem(object):
    """NOTE: This class is auto generated by OpenAPI Generator.
    Ref: https://openapi-generator.tech

    Do not edit the class manually.
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'category': 'str',
        'nft': 'TokenNft',
        'amount': 'float',
        'cashaddr': 'str'
    }

    attribute_map = {
        'category': 'category',
        'nft': 'nft',
        'amount': 'amount',
        'cashaddr': 'cashaddr'
    }

    def __init__(self, category=None, nft=None, amount=None, cashaddr=None, local_vars_configuration=None):  # noqa: E501
        """TokenBurnItem - a model defined in OpenAPI"""  # noqa: E501
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._category = None
        self._nft = None
        self._amount = None
        self._cashaddr = None
        self.discriminator = None

        self.category = category
        self.nft = nft
        if amount is not None:
            self.amount = amount
        if cashaddr is not None:
            self.cashaddr = cashaddr

    @property
    def category(self):
        """Gets the category of this TokenBurnItem.  # noqa: E501

        Token unique hexadecimal identifier, also the id of the token creation transaction  # noqa: E501

        :return: The category of this TokenBurnItem.  # noqa: E501
        :rtype: str
        """
        return self._category

    @category.setter
    def category(self, category):
        """Sets the category of this TokenBurnItem.

        Token unique hexadecimal identifier, also the id of the token creation transaction  # noqa: E501

        :param category: The category of this TokenBurnItem.  # noqa: E501
        :type category: str
        """
        if self.local_vars_configuration.client_side_validation and category is None:  # noqa: E501
            raise ValueError("Invalid value for `category`, must not be `None`")  # noqa: E501

        self._category = category

    @property
    def nft(self):
        """Gets the nft of this TokenBurnItem.  # noqa: E501


        :return: The nft of this TokenBurnItem.  # noqa: E501
        :rtype: TokenNft
        """
        return self._nft

    @nft.setter
    def nft(self, nft):
        """Sets the nft of this TokenBurnItem.


        :param nft: The nft of this TokenBurnItem.  # noqa: E501
        :type nft: TokenNft
        """

        self._nft = nft

    @property
    def amount(self):
        """Gets the amount of this TokenBurnItem.  # noqa: E501

        amount of fungible tokens to burn  # noqa: E501

        :return: The amount of this TokenBurnItem.  # noqa: E501
        :rtype: float
        """
        return self._amount

    @amount.setter
    def amount(self, amount):
        """Sets the amount of this TokenBurnItem.

        amount of fungible tokens to burn  # noqa: E501

        :param amount: The amount of this TokenBurnItem.  # noqa: E501
        :type amount: float
        """

        self._amount = amount

    @property
    def cashaddr(self):
        """Gets the cashaddr of this TokenBurnItem.  # noqa: E501

        address to return token and satoshi change to, default to the sender's cashaddr  # noqa: E501

        :return: The cashaddr of this TokenBurnItem.  # noqa: E501
        :rtype: str
        """
        return self._cashaddr

    @cashaddr.setter
    def cashaddr(self, cashaddr):
        """Sets the cashaddr of this TokenBurnItem.

        address to return token and satoshi change to, default to the sender's cashaddr  # noqa: E501

        :param cashaddr: The cashaddr of this TokenBurnItem.  # noqa: E501
        :type cashaddr: str
        """

        self._cashaddr = cashaddr

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TokenBurnItem):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, TokenBurnItem):
            return True

        return self.to_dict() != other.to_dict()
